mod:
    go mod tidy
    go mod download

lint:
    modernize ./...
    govulncheck ./...
    golangci-lint run ./...

lint-fix:
    modernize --fix ./...
    golangci-lint run --fix ./...
    govulncheck ./...
    nix fmt
